[package]
name = "automata"
license = "MIT"
description = "A library concerned with transition systems and automata for both finite and infinite words."
homepage = "https://github.com/leonbohn/automata"
repository = "https://github.com/leonbohn/automata"
keywords = [
    "omega-automata",
    "transition-system",
    "language",
    "hoa",
    "automata",
]
categories = ["mathematics", "science"]
readme = "README.md"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./docs-header.html"]

[dependencies]
# gryf = { git = "https://github.com/pnevyk/gryf", rev = "1efd3a2", optional = true }
petgraph = { version = "0.6.5", default-features = false, features = [
    "stable_graph",
] }
tracing = "0.1"
tracing-subscriber = "0.3"
itertools = "0.13.0"
tabled = { version = "0.15", features = ["ansi"] }
owo-colors = "4.0"
test-log = { version = "0.2", features = ["trace"] }
tempfile = { version = "3.10", optional = true }
paste = "1.0"
biodivine-lib-bdd = { version = "0.5", optional = true }
bit-set = "0.5"
bimap = "0.6"
fastrand = { version = "2", optional = true }
hoars = { version = "0.2", optional = true }
clap = { version = "4.5", optional = true }
indexmap = "2.2"


[features]
default = ["hoa", "graphviz", "random", "implementations"]
random = ["fastrand"]
hoa = ["dep:hoars", "biodivine-lib-bdd"]
graphviz = ["dep:tempfile"]
implementations = []
