[workspace]
members = [".", "hoars"]

[workspace.package]
license = "MIT or Apache-2.0"
edition = "2021"
homepage = "https://github.com/leonbohn/automata"
repository = "https://github.com/leonbohn/automata"
authors = ["León Bohn <bohn@lics.rwth-aachen.de>"]

[package]
name = "automata"
version = "0.1.0"
readme = "README.md"
description = "A library for transition systems and automata over (in)finite words."
keywords = [
    "transition-system",
    "language",
    "hoa",
    "automata",
    "omega-automata",
]
categories = ["mathematics", "science"]
edition.workspace = true
homepage.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
itertools = "0.13.0"
tabled = { version = "0.15", features = ["ansi"] }
owo-colors = "4.0"
test-log = { version = "0.2", features = ["trace"] }
tempfile = { version = "3.10", optional = true }
biodivine-lib-bdd = { version = "0.5", optional = true }
bit-set = "0.5"
bimap = "0.6"
fastrand = { version = "2", optional = true }
hoars = { version = "0.2", optional = true, path = "hoars" }
clap = { version = "4.5", optional = true }
indexmap = "2.2"
# default backend
petgraph = { version = "0.6.5", default-features = false, features = [
    "stable_graph",
] }
# experimental backend sometime?
# gryf = { git = "https://github.com/pnevyk/gryf", rev = "1efd3a2", optional = true }

[features]
default = ["hoa", "graphviz", "random"]
random = ["fastrand"]
hoa = ["dep:hoars", "biodivine-lib-bdd"]
graphviz = ["dep:tempfile"]
implementations = []
