[package]
name = "automata"
license = "MIT"
description = "A library concerned with transition systems and automata for both finite and infinite words."
homepage = "https://github.com/leonbohn/automata"
repository = "https://github.com/leonbohn/automata"
keywords = [
    "omega-automata",
    "transition-system",
    "language",
    "hoa",
    "automata",
]
categories = ["mathematics", "science"]
readme = "README.md"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
fxhash = "0.2"
itertools = "0.13.0"
tabled = { version = "0.15", features = ["ansi"] }
owo-colors = "4.0"
test-log = { version = "0.2", features = ["trace"] }
tempfile = { version = "3.10", optional = true }
paste = "1.0"
biodivine-lib-bdd = { version = "0.5", optional = true }
bit-set = "0.5"
bimap = "0.6"
fastrand = { version = "2", optional = true }
hoars = { version = "0.2", optional = true }
clap = { version = "4.5", optional = true }

[features]
default = ["hoa", "graphviz", "random", "minimize"]
random = ["fastrand"]
minimize = []
hoa = ["dep:hoars", "biodivine-lib-bdd"]
graphviz = ["dep:tempfile"]
oai-bin = ["clap"]
linked_list_ts = []

[dev-dependencies]
lazy_static = "1.4"
criterion = { version = "0.5", features = ["html_reports"] }
# iai = { git = "https://github.com/sigaloid/iai", rev = "6c83e942" }

[[bench]]
name = "ts"
harness = false

[[bin]]
name = "oai"
path = "bin/oai.rs"
required-features = ["oai-bin"]
