[package]
name = "automata"
version = "0.2.0"
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
fxhash = "0.2"
itertools = "0.12"
tabled = { version = "0.15", features = ["ansi"] }
owo-colors = "4.0"
test-log = { version = "0.2", features = ["trace"] }
tempfile = { version = "3.10", optional = true }
paste = "1.0"
biodivine-lib-bdd = { version = "0.5", optional = true }
bit-set = "0.5"
bimap = "0.6"
fastrand = { version = "2", optional = true }
hoars = { git = "https://github.com/leonbohn/hoars", optional = true }

[features]
default = ["hoa", "graphviz", "random", "minimize"]
random = ["fastrand"]
minimize = []
hoa = ["dep:hoars", "biodivine-lib-bdd"]
graphviz = ["dep:tempfile"]

[dev-dependencies]
lazy_static = "1.4"
criterion = { version = "0.5", features = ["html_reports"] }
# iai = { git = "https://github.com/sigaloid/iai", rev = "6c83e942" }

[[bench]]
name = "ts"
harness = false
